# Generated by Django 5.1.3 on 2024-12-05 13:52

import django.db.models.deletion
import django.utils.timezone
import foods.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[foods.models.validate_past_date])),
                ('eaten_at', models.TimeField(default=django.utils.timezone.now)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=50)),
                ('food_name', models.CharField(max_length=50)),
                ('portion_size', models.CharField(max_length=50)),
                ('discomfort', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50)),
                ('is_trigger', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Unsure')], max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-eaten_at'],
            },
        ),
    ]
