# Generated by Django 5.1.3 on 2024-11-26 15:42

import django.utils.timezone
import foods.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, validators=[foods.models.validate_past_date]),
        ),
    ]
