# Generated by Django 5.1.3 on 2024-12-04 14:35

import foods.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='date',
            field=models.DateField(validators=[foods.models.validate_past_date]),
        ),
    ]
