# Generated by Django 5.1.3 on 2024-11-26 15:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_food_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='eaten_at',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
