# Generated by Django 5.1.3 on 2024-11-26 15:52

import django.utils.timezone
import foods.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_alter_food_eaten_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['-date', '-eaten_at']},
        ),
        migrations.AlterField(
            model_name='food',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[foods.models.validate_past_date]),
        ),
    ]
