# Generated by Django 5.1.3 on 2024-11-27 10:09

import django.db.models.deletion
import django.utils.timezone
import medications.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('5-ASAs', [('MESALAZINE_ORAL', 'Mesalazine (Oral)'), ('MESALAZINE_TOPICAL', 'Mesalazine (Topical)'), ('SULFASALAZINE', 'Sulfasalazine'), ('BALSALAZIDE', 'Balsalazide'), ('OLSALAZINE', 'Olsalazine')]), ('Corticosteroids', [('PREDNISOLONE', 'Prednisolone'), ('BUDESONIDE', 'Budesonide'), ('HYDROCORTISONE', 'Hydrocortisone'), ('BECLOMETHASONE', 'Beclomethasone')]), ('Immunomodulators', [('AZATHIOPRINE', 'Azathioprine'), ('MERCAPTOPURINE', 'Mercaptopurine'), ('METHOTREXATE', 'Methotrexate'), ('CYCLOSPORINE', 'Cyclosporine'), ('TACROLIMUS', 'Tacrolimus')]), ('Biologics', [('INFLIXIMAB', 'Infliximab'), ('ADALIMUMAB', 'Adalimumab'), ('GOLIMUMAB', 'Golimumab'), ('VEDOLIZUMAB', 'Vedolizumab'), ('USTEKINUMAB', 'Ustekinumab'), ('RISANKIZUMAB', 'Risankizumab')]), ('JAK Inhibitors', [('TOFACITINIB', 'Tofacitinib'), ('UPADACITINIB', 'Upadacitinib')])], max_length=50)),
                ('dosage', models.CharField(max_length=50)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('twice_daily', 'Twice Daily'), ('three_times_daily', 'Three Times Daily'), ('four_times_daily', 'Four Times Daily'), ('weekly', 'Weekly'), ('every_other_week', 'Every Other Week'), ('monthly', 'Monthly'), ('as_needed', 'As Needed')], max_length=20)),
                ('start_date', models.DateField(validators=[medications.models.validate_past_date])),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-active', '-start_date'],
            },
        ),
    ]
