# Generated by Django 5.1.3 on 2024-11-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='type',
            field=models.CharField(choices=[('pain', 'Abdominal Pain'), ('blood', 'Blood in Stool'), ('urgency', 'Urgency'), ('diarrhoea', 'Diarrhoea'), ('fatigue', 'Fatigue'), ('joint_pain', 'Joint Pain'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
